### PR TITLE
After adding MTA attribute for NUnit Castle.Transactions.Tests passed

### PR DESCRIPTION
**Pull request by ghost**
One down! Many more to go!

### CODE REVIEW

**Comment by vladapokorny** [comment]
@fir3pho3nixx You probably forgot to add file TestAssemblyInfo.cs, but when I added `[assembly: Apartment(ApartmentState.STA)]` attribute, Castle.Transaction.Tests passed.

**Comment by ghost** [comment]
Correct! Let me add it. Not having CI on this is doing me. Can I raise an issue for adding appveyor?

**Comment by vladapokorny** [comment]
@fir3pho3nixx Changes merged. I still have priority on resolving unit tests, but I agree with creating an issue for adding appveyor.

**Comment by ghost** [comment]
Still cannot raise issues on this project, so I noted them down in the PR.

**Pull request merged**
